#!/bin/bash

# ── Config ──────────────────────────────────────────────
SKILL_FILE=".claude/skills/doc-agent.md"
DOCS_DIR="docs"
CHANGELOG="docs/CHANGELOG.md"
JOURNEY="docs/JOURNEY.md"
# ────────────────────────────────────────────────────────

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

if ! command -v claude &> /dev/null; then
  echo -e "${YELLOW}⚠ Claude Code not found — skipping doc update.${NC}"
  exit 0
fi

# ── Gather commit context ──────────────────────────────
COMMIT_MSG=$(git log -1 --pretty=%s)
COMMIT_HASH=$(git log -1 --pretty=%h)
COMMIT_DATE=$(date '+%Y-%m-%d %H:%M')

# Extract type and scope from conventional commit message
# e.g. feat(market-table): add sortable columns → type=feat, scope=market-table
COMMIT_TYPE=$(echo "$COMMIT_MSG" | sed -E 's/^([a-z]+)\(.+\):.+/\1/')
COMMIT_SCOPE=$(echo "$COMMIT_MSG" | sed -E 's/^[a-z]+\(([^)]+)\):.+/\1/')
COMMIT_DESC=$(echo "$COMMIT_MSG" | sed -E 's/^[a-z]+\([^)]+\): (.+)/\1/')

# Get changed TS/TSX files
# On first commit HEAD~1 doesn't exist — fall back to listing all tracked TS files
if git rev-parse HEAD~1 > /dev/null 2>&1; then
  CHANGED_FILES=$(git diff HEAD~1 HEAD --name-only 2>/dev/null | \
    grep -E '\.(ts|tsx)$' | \
    grep -v 'node_modules\|\.d\.ts\|vite-env')
else
  CHANGED_FILES=$(git ls-tree -r HEAD --name-only 2>/dev/null | \
    grep -E '\.(ts|tsx)$' | \
    grep -v 'node_modules\|\.d\.ts\|vite-env')
fi

FILE_LIST=$(echo "$CHANGED_FILES" | sed 's/^/  - /')
# Get diff — handle first commit case
if git rev-parse HEAD~1 > /dev/null 2>&1; then
  DIFF=$(git diff HEAD~1 HEAD --unified=3 -- $CHANGED_FILES 2>/dev/null | head -300)
else
  DIFF=$(git show HEAD --unified=3 -- $CHANGED_FILES 2>/dev/null | head -300)
fi

# Full git log for JOURNEY grouping
GIT_LOG=$(git log --oneline --no-decorate 2>/dev/null | head -50)

# Load skill instructions
SKILL_INSTRUCTIONS=""
if [ -f "$SKILL_FILE" ]; then
  SKILL_INSTRUCTIONS=$(cat "$SKILL_FILE")
fi

echo ""
echo -e "${CYAN}── Claude Doc Agent ────────────────────────────────${NC}"
echo -e "  Commit : ${CYAN}${COMMIT_TYPE}(${COMMIT_SCOPE})${NC}: ${COMMIT_DESC}"
echo -e "  Hash   : ${COMMIT_HASH}"
echo -e "  Files  : $(echo "$CHANGED_FILES" | grep -c . || echo 0) TS/TSX files changed"

mkdir -p "$DOCS_DIR"

# Seed files if they don't exist
[ ! -f "$CHANGELOG" ] && echo -e "# Changelog\n" > "$CHANGELOG"
[ ! -f "$JOURNEY" ]   && echo -e "# Project Journey\n> Auto-generated by Claude Code post-commit agent\n" > "$JOURNEY"

# ── Build the prompt ───────────────────────────────────
PROMPT="You are a documentation agent running after a git commit in the Clara Market Dashboard project.

${SKILL_INSTRUCTIONS}

## This commit
- Message : ${COMMIT_MSG}
- Type    : ${COMMIT_TYPE}
- Scope   : ${COMMIT_SCOPE}
- Desc    : ${COMMIT_DESC}
- Hash    : ${COMMIT_HASH}
- Date    : ${COMMIT_DATE}

## Changed files
${FILE_LIST}

## Diff (truncated to 300 lines)
\`\`\`diff
${DIFF}
\`\`\`

## Full git log (most recent first)
\`\`\`
${GIT_LOG}
\`\`\`

---

## Your tasks

### Task 1 — JSDoc
For any exported function, hook, or component that was added or changed:
- Add or update JSDoc comments in the source file
- Max 2 sentences per symbol. Be precise, not verbose.

### Task 2 — CHANGELOG.md
Prepend exactly one line to docs/CHANGELOG.md (newest first):
Format: \`- [DATE HASH] type(scope): description\`
Example: \`- [2025-01-15 14:32 a1b2c3] feat(market-table): add sortable columns\`

### Task 3 — JOURNEY.md
This is the most important task. Update docs/JOURNEY.md so Clara's evaluators
can follow the full development story from first commit to now.

Rules for JOURNEY.md:
- Group commits by scope (e.g. ## setup, ## types, ## api, ## market-table)
- Under each scope, write a SHORT narrative paragraph (3-5 sentences) in plain English
  explaining: what was built, why it was done this way, and any key decisions made
- List the commits that belong to that scope below the paragraph
- If the scope section already exists, UPDATE it — do not duplicate it
- Write for a technical evaluator who hasn't seen the code
- Tone: clear, confident, engineering-focused. Not a diary entry.

Example format for JOURNEY.md:
\`\`\`
## setup
Bootstrapped with Vite and React 18 + TypeScript strict mode. Chose Vite over
CRA for its faster dev server and active maintenance. TanStack Query was added
upfront as the data fetching layer to centralize caching and background refresh
from the start rather than refactoring later.

- chore(setup): scaffold Vite + React + TypeScript [a1b2c3]
- chore(setup): install TanStack Query and Recharts [b2c3d4]

## types
Defined all CoinGecko API response types before writing any API calls. This
ensures TypeScript catches shape mismatches at the boundary rather than inside
components. Types are derived from the actual API response, not guessed.

- feat(types): add CoinMarket and SparklineData types [c3d4e5]
\`\`\`

### Rules
- Only write to docs/ and add JSDoc — never touch business logic
- If nothing changed worth documenting in JSDoc, skip Task 1
- Always complete Task 2 and Task 3
"

echo -e "  Running Claude Code in background..."
echo ""

claude -p "$PROMPT" \
  --allowedTools "Read,Edit,Write,Bash(mkdir*),Bash(date*)" \
  > /tmp/claude-doc-agent.log 2>&1 &

CLAUDE_PID=$!
sleep 1

if kill -0 $CLAUDE_PID 2>/dev/null; then
  echo -e "${GREEN}✔ Doc agent running in background (PID: ${CLAUDE_PID})${NC}"
  echo -e "  Updates : ${CYAN}docs/CHANGELOG.md${NC} + ${CYAN}docs/JOURNEY.md${NC}"
  echo -e "  Log     : ${CYAN}tail -f /tmp/claude-doc-agent.log${NC}"
else
  echo -e "${YELLOW}⚠ Doc agent finished — check /tmp/claude-doc-agent.log${NC}"
fi

echo -e "${CYAN}───────────────────────────────────────────────────${NC}"
echo ""
exit 0
